### ISSUE TITLE
Oauth2

### ISSUE THREAD

**Issue by bouke-steemers** [teamleadercrm/sdk-js#173]
Hi,

maybe a newbe question, but how do I autorize my app with teamleader using OAuth2?

Bouke

**Comment by rathesDot** [comment]
Hey Bouke,

did you see the documentation here? https://developer.teamleader.eu/#/introduction/authentication

Note, that this the package does not support you with the OAuth2 flow

**Comment by laurenskling** [comment]
Would have loved to see an Oauth flow inside of this package as well :) Any chance of happening soon?

**Comment by ArnaudWeyts** [comment]
@laurenskling Hey, thanks for flagging! At the moment adding this flow isn't a big priority for us, but we are planning some bigger changes to this package to bring it up to standards (Typescript, some refactoring around the pre-defined actions, request cancellation, etc). No clear ETA on this at the moment, but we are very much open to pull requests!
