### ISSUE TITLE
RFC: side loading

### ISSUE THREAD

**Issue by duivvv** [teamleadercrm/sdk-js#31]
## What?

How do we include side loading in sdk-js?

## Proposal

This proposal will introduce breaking changes.

Using the example of https://teamleader-engineering.blogin.co/single-post.php?id=54221

Using the `projects.list` endpoint, triggering a `customer` side-load.

_endpoint_:
https://api.teamleader.eu/projects.list?include=customer

_result_:
```json

{
    "data": [
        {
            "id": "8ef941ad-214f-0721-b818-f678e53a1714",
            "title": "New company website",
            "status": "active",
            "starts_on": "2016-02-04",
            "customer": {
                "type": "company",
                "id": "b5d55370-f649-0bfb-9010-03132f9eaae8"
            }
        },
        {
            "id": "58bcd4da-f68e-053e-9b1c-3cb6c5796867",
            "title": "New company website",
            "status": "active",
            "starts_on": "2016-02-04",
            "customer": {
                "type": "company",
                "id": "0709fc3e-e918-00d5-a113-ba00a33102ca"
            },
        },
        {
            "id": "795be9dd-ee91-070e-b212-5bf5cb1f57d3",
            "title": "azerty",
            "status": "active",
            "starts_on": "2018-09-13",
            "customer": {
                "type": "contact",
                "id": "29c7a647-bbaf-0807-9722-233e34891f11"
            },
        }
    ],
    "includes": {
        "company": [
            {
                "id": "0709fc3e-e918-00d5-a113-ba00a33102ca",
                "name": "Peterson Paper",
            },
            {
                "id": "b5d55370-f649-0bfb-9010-03132f9eaae8",
                "name": "Summers Digital Ltd",
            }
        ],
        "contact": [
            {
                "id": "29c7a647-bbaf-0807-9722-233e34891f11",
                "first_name": "Barry",
                "last_name": "Green",
            },
        ]
    }
}

```

### 1 / Triggering a side-load

_edited after reading https://github.com/teamleadercrm/sdk-js/issues/31#issuecomment-437009287_

We would pass include as the first parameter in the actual function call

```js
projects.list({ include: 'customer' }, { response: normalize });
```

_with extra param_
```js
projects.list({ filter: { status: 'active' },  include: 'customer' }, { response: normalize });
```

`include` can be a string (1 include) or an array of strings (multiple includes). 

### 2 / Parsing the result

We can handle the way the result is parsed with plugins 
I think we should allow for 2 options

### 2.1 / Return the data normalized (`normalize` plugin)

Normalize all data under within the specific domain (key / value).

We would need to change the normalize plugin a bit to achieve this output.

```json

{
    "projects": {
        "8ef941ad-214f-0721-b818-f678e53a1714": {
            "id": "8ef941ad-214f-0721-b818-f678e53a1714",
            "title": "New company website",
            "status": "active",
            "starts_on": "2016-02-04",
            "customer": {
                "type": "company",
                "id": "b5d55370-f649-0bfb-9010-03132f9eaae8"
            }
        },
        "58bcd4da-f68e-053e-9b1c-3cb6c5796867": {
            "id": "58bcd4da-f68e-053e-9b1c-3cb6c5796867",
            "title": "New company website",
            "status": "active",
            "starts_on": "2016-02-04",
            "customer": {
                "type": "company",
                "id": "0709fc3e-e918-00d5-a113-ba00a33102ca"
            },
        },
        "795be9dd-ee91-070e-b212-5bf5cb1f57d3": {
            "id": "795be9dd-ee91-070e-b212-5bf5cb1f57d3",
            "title": "azerty",
            "status": "active",
            "starts_on": "2018-09-13",
            "customer": {
                "type": "contact",
                "id": "29c7a647-bbaf-0807-9722-233e34891f11"
            },
        }
    },
    "companies": {
        "0709fc3e-e918-00d5-a113-ba00a33102ca": {
            "id": "0709fc3e-e918-00d5-a113-ba00a33102ca",
            "name": "Peterson Paper",
        },
        "b5d55370-f649-0bfb-9010-03132f9eaae8": {
            "id": "b5d55370-f649-0bfb-9010-03132f9eaae8",
            "name": "Summers Digital Ltd",
        }
    },
    "contacts": {
        "29c7a647-bbaf-0807-9722-233e34891f11": {
            "id": "29c7a647-bbaf-0807-9722-233e34891f11",
            "first_name": "Barry",
            "last_name": "Green",
        }
    }
}
````

Issue here, the endpoint returns `company` / `contact` instead of `companies` / `contacts` in the `includes` key. I could easily extract **projects** from the domain name.

This would allow destructuring the received data from the response

```js 

const { projects, contacts, companies } = await projects.list(undefined, { include: 'customer', plugins: { response: normalize } });

// everything byId.

```

Changing the plugin would also mean you'd need to change the destructuring if you don't use any side loading.

```js 

const { projects } = await projects.list();

```

#### Question:

- How do we handle the singular/plural issue?

### 2.2 / Return the data merged (`merge` plugin)

The `merge` plugin would create this output:

```json

{
    "data": [
        {
            "id": "8ef941ad-214f-0721-b818-f678e53a1714",
            "title": "New company website",
            "status": "active",
            "starts_on": "2016-02-04",
            "customer": {
                "type": "company",
                "id": "b5d55370-f649-0bfb-9010-03132f9eaae8",
                "name": "Summers Digital Ltd"
            }
        },
        {
            "id": "58bcd4da-f68e-053e-9b1c-3cb6c5796867",
            "title": "New company website",
            "status": "active",
            "starts_on": "2016-02-04",
            "customer": {
                "type": "company",
                "id": "0709fc3e-e918-00d5-a113-ba00a33102ca",
                "name": "Peterson Paper"
            }
        },
        {
            "id": "795be9dd-ee91-070e-b212-5bf5cb1f57d3",
            "title": "azerty",
            "status": "active",
            "starts_on": "2018-09-13",
            "customer": {
                "type": "contact",
                "id": "29c7a647-bbaf-0807-9722-233e34891f11",
                "first_name": "Barry",
                "last_name": "Green"
            }
        }
    ]
}

````

I would keep the types in there for rendering purposes on the FE.

#### Question:

- Do we normalize the root level, or keep the response structure (array)? Is this the output we should generate by combining `merge` & `normalize` plugin?

```json

{
    "data": {
        "8ef941ad-214f-0721-b818-f678e53a1714": {
            "id": "8ef941ad-214f-0721-b818-f678e53a1714",
            "title": "New company website",
            "status": "active",
            "starts_on": "2016-02-04",
            "customer": {
                "type": "company",
                "id": "b5d55370-f649-0bfb-9010-03132f9eaae8",
                "name": "Summers Digital Ltd"
            }
        },
        "58bcd4da-f68e-053e-9b1c-3cb6c5796867": {
            "id": "58bcd4da-f68e-053e-9b1c-3cb6c5796867",
            "title": "New company website",
            "status": "active",
            "starts_on": "2016-02-04",
            "customer": {
                "type": "company",
                "id": "0709fc3e-e918-00d5-a113-ba00a33102ca",
                "name": "Peterson Paper"
            },
        },
        "795be9dd-ee91-070e-b212-5bf5cb1f57d3": {
            "id": "795be9dd-ee91-070e-b212-5bf5cb1f57d3",
            "title": "azerty",
            "status": "active",
            "starts_on": "2018-09-13",
            "customer": {
                "type": "contact",
                "id": "29c7a647-bbaf-0807-9722-233e34891f11",
                "first_name": "Barry",
                "last_name": "Green"
            },
        }
    }
}

```

**Comment by nickwaelkens** [comment]
In the current situation, the first argument of (eg.) the `projects.info` method is the request parameters. If none are required, eg. for `projects.list`, we pass `undefined`. In my personal opinion, `includes` has to be seen as a request parameter (it literally is one), so it would make more sense to add it there.

```js
projects.list(undefined, { include: 'customer', plugins: { response: normalize } });
projects.info({ id: '8ef941ad-214f-0721-b818-f678e53a1714' }, { include: 'customer', plugins: { response: normalize } });
```

```js
projects.list({ include: 'customer' }, { response: normalize });
projects.info({ id: '8ef941ad-214f-0721-b818-f678e53a1714', include: 'customer' }, { response: normalize });
```

Less of a breaking change with this approach, but like I said, just my opinion.

**Comment by duivvv** [comment]
@nickwaelkens That makes a lot of sense. 👍

**Comment by timdegroote** [comment]
Nice writeup! 👍 

What also might be useful is a convenience 'configuration' option to sideload everything for an endpoint? It's often the case that we need everything and this could be something the SDK can help with. Based on the endpoint the sdk would then add the appropriate include parameter to the request.
`projects.list(undefined, { sideload: true })`

Another posibility would be to make this into a request plugin, then the options of the config object wouldn't change either though the plugin would need to be made aware of which endpoint is being requested:
`projects.list(undefined, plugins: { request: [sideload] })`

A downside to this would be though that it will sideload everything. If in the beginning you need everything but let's say the api changes to include more links to other resources. If you then update the sdk and don't really review where you've used this option then you'll be loading data which you don't need.

**Comment by duivvv** [comment]
@timdegroote might make sense to make it explicit now & add it as plugin later on

**Comment by nickwaelkens** [comment]
<sup>Just thinking out loud here, bear with me...</sup>

First of all, I understand that this way of requesting more information through a [`?include=` GET parameter is a standard](https://jsonapi.org/format/#fetching-includes) and I greatly appreciate the time and effort @jdww, @jenssegers and @stivni have put into this. Yet, it feels like we are reinventing the wheel and I _really_ think we should (re-)investigate how our front-end apps can consume our API in an intuitive and flexible way (see https://github.com/teamleadercrm/sdk-js/issues/31#issuecomment-437017104 – @timdegroote has a valid point, under-/over-fetching is always an issue!). 

Granted, this is not the ideal place to discuss this but–what about GraphQL? The `?include` parameter is not documented as of yet anyway; why not go the extra mile and make our front-end applications (mobile included!) easier to understand/reason about?

If not (the most likely path), can we at least try and make sure the output we get from `sdk-js` "looks like" whatever GraphQL would return? That way, in a potential future, it would be easier to make the switch.

**Comment by duivvv** [comment]
@nickwaelkens 

> If not (the most likely path), can we at least try and make sure the output we get from sdk-js "looks like" whatever GraphQL would return? That way, in a potential future, it would be easier to make the switch.

Not sure how that would work (any ideas?). GraphQL has a highly flexible syntax.

**Comment by duivvv** [comment]
I agree GraphQL is the ultimate end-goal, but it might take a while till we're there. Let's implement the side loading now, and start a discussion regarding GraphQL. No need to convince me of the benefits there ;)

**Comment by duivvv** [comment]
@LennertBlommaert 

The way GraphQL returns data is nothing too exotic, just nested data (2.2 in my proposal).

The problem GraphQL solves is the under/over fetching.

**Comment by jenssegers** [comment]
@nickwaelkens After checking the code it seems that that is not the case, YET. Changing our gateway to get it from either GET or POST should be quite easy. So please let this not be an obstacle for the SDK!

**Comment by duivvv** [comment]
I don’t think the GET would be a huge problem, it’s passing it as a querystring on the call, right?

**Comment by ArnaudWeyts** [comment]
Okay, let's breathe some life into this RFC again:

> How do we handle the singular/plural issue?

I can't think of any other way than having a mapping / changing the sideloading so the reference types are already plural. It's not ideal as @lowiebenoot pointed out here https://github.com/teamleadercrm/react-hooks-api/pull/12#discussion_r292859260.

> Do we normalize the root level, or keep the response structure (array)? Is this the output we should generate by combining merge & normalize plugin?

I think the output listed below this doesn't need the "projects" key when merging

**Comment by duivvv** [comment]
> I think the output listed below this doesn't need the "projects" key when merging

👍, edited it

**Comment by lowiebenoot** [comment]
What about just using the singular? So what the api actually returns.
In my opinion, using a map is not really maintainable (and also a bit of an issue with undocumented endpoints). 

> changing the sideloading so the reference types are already plural

That doesn't really change the issue, right? It only moves it to another place, or do I misunderstand it?

**Comment by ArnaudWeyts** [comment]
@lowiebenoot I think our frontend hands are pretty tied if you want to be able to use custom domains. Domain needs to `===` type. I looked at the `api-gateway` and they actually use the exact same reversed map to translate from `types` to `domains` 🤷‍♂ 

maybe @jenssegers can shed some light on why they also decided to use a map in the api-gateway?

**Comment by ArnaudWeyts** [comment]
Closing this issue until a need for it arises.
