### ISSUE TITLE
RFC: pagination

### ISSUE THREAD

**Issue by duivvv** [teamleadercrm/sdk-js#32]
## What

How do we handle loading all results of a specific API request via sdk-js?

In some specific cases, we want to be able to fetch all the results without handling the pagination logic yourself or via the UI.

For example, the case of the month view in the calendar. We would need to see all the events there, paginating them wouldn't work in this case.

## Situation

Currently, we can receive a maximum of **100 items** in **1 request**.

We don't have any pagination info in the response, so we would need to fetch the next page **sequentially** until there the amount of data is **smaller than the maximum** (could be a lot better).

## Proposal

It doesn't make sense to solve this with a plugin since plugins have a `data => data` signature.

I would propose to move plugins into a general options object and allow for the option to add a `fetchAll` (feel free to suggest another name).

> @nickwaelkens I don't think we can tackle this param in any other way (see discussion in the previous RFC)

Meaning we would need to move the plugins into this object as well.

example:

```js
events.list({ filter: '...' }, { plugins: { response: normalize }, fetchAll: true });
```

Passing this option would indicate that sdk-js needs to make multiple requests if required & respect the provided plugins.

**Comment by duivvv** [comment]
@nickwaelkens what does the self-assigning mean? :)

**Comment by nickwaelkens** [comment]
@duivvv It's so I don't forget to check this!

**Comment by Kemosabert** [comment]
As far as I am concerned and my knowledge goes, this feature would be very useful and the way you propose to do it here also looks good to me. Can't wait for the implementation.

**Comment by nickwaelkens** [comment]
Why not take it a step further and ask for a certain number to return, if possible? Like `LIMIT` in SQL?

Imagine: you have 10k contacts in your CRM and you've passed the `fetchAll` flag. That's 100 requests returning 100 contacts each?

**Comment by duivvv** [comment]
- < 100 this can be handled with the size parameter when doing the request.
- > 100 you would need multiple requests and would need to handle the pagination yourself (would be quite complicated I think, you would need to handle the paginations with the request, since page 1, 2, 3 won't be correct)

I'm not sure in what scenario you would need to fetch all 10k contacts?

**Comment by nickwaelkens** [comment]
I was just thinking out loud, you're probably right though. Disregard my comment!

**Comment by duivvv** [comment]
No worries, this is what this issue is for :)

I like the idea, but I think it would be difficult (currently)
